### ISSUE TITLE
Installation error: perl-xml-parser

### ISSUE THREAD

**Issue by crimBubble** [simonorozcoarias/Inpactor2#1]
Hi @simonorozcoarias,
there was an error when installing Inpactor2.

Error message when installing with conda:

```
$conda env create -f Inpactor2.yml
...
  - zlib==1.2.11=h516909a_1010 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - zstd==1.5.0=ha95c52a_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
Your installed version is: 2.31
```

Error message when installing with mamba:
```
$mamba env create -f Inpactor2.yml
...
Could not solve for environment specs
Encountered problems while solving:
  - package perl-xml-parser-2.44-4 requires perl >=5.22.0,<5.23.0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

Removing the specific version number in the yml-file resolved the issue.
line 170:  `- perl-xml-parser=2.44=4` to `  - perl-xml-parser`

After the change the installation worked, and the testing showed similar results to the ones provided. Maybe consider changing the yml-file if this error is consistent to others.

Also the in the yml-file provided prefix `prefix: /home/bioml/anaconda3/envs/Inpactor2` is specific to your machine and might lead to problems when installing on other machines for other users. I deleted this line in the yml-file and did not have any issues.

However, your tool looks really promising and I am looking forward to test and use it.

**Comment by simonorozcoarias** [comment]
Hi @crimBubble Thank you for using Inpactor2. Yes, other users reported the same issue so I modified the YML to remove that dependency requirement. I hope Inpactor2 will be use for you !!
