### ISSUE TITLE
Memory usage RM step

### ISSUE THREAD

**Issue by crimBubble** [simonorozcoarias/Inpactor2#3]
Hi @simonorozcoarias,
I am trying to run Inpactor2 on my genome, but I have some issues regarding memory usage in the RepeatMasker step. RAM usage goes up to >50GB per thread while using 32 threads (see the attached image). I am already only using single scaffolds as input with the largest being only 450Mb. Did you experience a similar behaviour before? And can you think of a different solution then just using less threads to prevent single subprocesses getting killed?

![grafik](https://github.com/simonorozcoarias/Inpactor2/assets/45664228/d4dd2ab7-df78-4336-9a59-90f176371b7e)

**Comment by simonorozcoarias** [comment]
Hi @crimBubble,

Thank you for using Inpactor2. How big and how full of TE is your genome? how many sequences did you get from Inpactor2? Maybe can be helpful to generate the library without  the annotation step. Then, you can try to reduce the redundancy to generate a library with less  sequences and finally try to run RepeatMasker independely.

**Comment by crimBubble** [comment]
Thanks for the quick reply. I will run without annotation and have a look. As I am running on each scaffold individually anyway this seems to be a reasonable decision. I tried with the whole assembly at first, but the "suppressing non-maximal predictions"-step was running over 8 weeks or so, before the server was restarted for maintenance.
Running individually, for scaffold 1 (about 450Mb) Inpactor predicted almost 20k retrotransposons and RM reported 88.4% dispersed elements with almost 500k hits. I guess my genome is not necessarily the easiest to work with.

**Comment by simonorozcoarias** [comment]
Wow, it seems like a very repetitive genome. So, probably yes, it would be better remove the redundancy as much as you can before doing the annotation.
