### ISSUE TITLE
The information regarding terminal and internal sequences is missing

### ISSUE THREAD

**Issue by CSU-KangHu** [simonorozcoarias/Inpactor2#5]
Hi @simonorozcoarias,
Thanks for developing Inpactor2. Inpactor2 generates two output files, **Inpactor2_library.fasta** and **Inpactor2_predictions.tab**, both of which only describe intact LTRs. Is it possible to output the position and sequences for terminal and internal sequences similar to LTR_finder? Can you provide an LTR library containing terminal and internal sequences?

**Comment by simonorozcoarias** [comment]
Hi !!
Thank you for using Inpactor2. The software was designed to generate a LTR retrotransposons library with the intact sequences. So, Inpactor2 doesn't generate LTR and internal sections separately. Nevertheless, using the Inpactor2_library.fasta file you can detect the LTR coordinates, aligning each sequences to itself, and getting the longer alignments (starting at the very beginning or at the very end). You can do that with BLASTn or any other alignment tool.

I hope this information is useful for you.

Best regards,
